from eudplib import *


VChatIndex = EUDArray(8)
VKeyDown_F = EUDArray(8)
VKeyDown_ENTER = EUDArray(8)
VKeyDown_0 = EUDArray(8)
VKeyDown_1 = EUDArray(8)
VKeyDown_2 = EUDArray(8)
VKeyDown_3 = EUDArray(8)
VKeyDown_4 = EUDArray(8)
VKeyDown_5 = EUDArray(8)
VKeyDown_6 = EUDArray(8)
VKeyDown_7 = EUDArray(8)
VKeyDown_8 = EUDArray(8)
VKeyDown_9 = EUDArray(8)
VKeyDown_SP21 = EUDArray(8)
VKeyDown_SP3 = EUDArray(8)
VKeyDown_W = EUDArray(8)
VKeyDown_Z = EUDArray(8)
VKeyDown_X = EUDArray(8)
VKeyPress_LSHIFT = EUDArray(8)
VMouseDown_L = EUDArray(8)
VKeyPress_ENTER = EUDArray(8)
VKeyPress_F = EUDArray(8)
VKeyPress_G = EUDArray(8)
VKeyPress_SP1 = EUDArray(8)
VKeyPress_E = EUDArray(8)
VKeyPress_SP5 = EUDArray(8)
VKeyPress_B = EUDArray(8)
VKeyPress_C = EUDArray(8)
VKeyPress_SP6 = EUDArray(8)
VKeyPress_H = EUDArray(8)
VKeyPress_I = EUDArray(8)
VKeyPress_J = EUDArray(8)
VKeyPress_K = EUDArray(8)
VKeyPress_L = EUDArray(8)
VKeyPress_SP3 = EUDArray(8)
VKeyPress_O = EUDArray(8)
VKeyPress_SP4 = EUDArray(8)
VKeyPress_Q = EUDArray(8)
VKeyPress_R = EUDArray(8)
VKeyPress_S = EUDArray(8)
VKeyPress_T = EUDArray(8)
VKeyPress_SP2 = EUDArray(8)
VKeyPress_V = EUDArray(8)
VKeyPress_W = EUDArray(8)
VKeyPress_X = EUDArray(8)
VKeyPress_Y = EUDArray(8)
VKeyPress_Z = EUDArray(8)

def Reg():
    print('... TERegVar ...')
    EUDRegisterObjectToNamespace("VKeyDown_F", VKeyDown_F)
    EUDRegisterObjectToNamespace("VKeyDown_ENTER", VKeyDown_ENTER)
    EUDRegisterObjectToNamespace("VKeyDown_0", VKeyDown_0)
    EUDRegisterObjectToNamespace("VKeyDown_1", VKeyDown_1)
    EUDRegisterObjectToNamespace("VKeyDown_2", VKeyDown_2)
    EUDRegisterObjectToNamespace("VKeyDown_3", VKeyDown_3)
    EUDRegisterObjectToNamespace("VKeyDown_4", VKeyDown_4)
    EUDRegisterObjectToNamespace("VKeyDown_5", VKeyDown_5)
    EUDRegisterObjectToNamespace("VKeyDown_6", VKeyDown_6)
    EUDRegisterObjectToNamespace("VKeyDown_7", VKeyDown_7)
    EUDRegisterObjectToNamespace("VKeyDown_8", VKeyDown_8)
    EUDRegisterObjectToNamespace("VKeyDown_9", VKeyDown_9)
    EUDRegisterObjectToNamespace("VKeyDown_SP21", VKeyDown_SP21)
    EUDRegisterObjectToNamespace("VKeyDown_SP3", VKeyDown_SP3)
    EUDRegisterObjectToNamespace("VKeyDown_W", VKeyDown_W)
    EUDRegisterObjectToNamespace("VKeyDown_Z", VKeyDown_Z)
    EUDRegisterObjectToNamespace("VKeyDown_X", VKeyDown_X)
    EUDRegisterObjectToNamespace("VKeyPress_LSHIFT", VKeyPress_LSHIFT)
    EUDRegisterObjectToNamespace("VMouseDown_L", VMouseDown_L)
    EUDRegisterObjectToNamespace("VKeyPress_ENTER", VKeyPress_ENTER)
    EUDRegisterObjectToNamespace("VKeyPress_F", VKeyPress_F)
    EUDRegisterObjectToNamespace("VKeyPress_G", VKeyPress_G)
    EUDRegisterObjectToNamespace("VKeyPress_SP1", VKeyPress_SP1)
    EUDRegisterObjectToNamespace("VKeyPress_E", VKeyPress_E)
    EUDRegisterObjectToNamespace("VKeyPress_SP5", VKeyPress_SP5)
    EUDRegisterObjectToNamespace("VKeyPress_B", VKeyPress_B)
    EUDRegisterObjectToNamespace("VKeyPress_C", VKeyPress_C)
    EUDRegisterObjectToNamespace("VKeyPress_SP6", VKeyPress_SP6)
    EUDRegisterObjectToNamespace("VKeyPress_H", VKeyPress_H)
    EUDRegisterObjectToNamespace("VKeyPress_I", VKeyPress_I)
    EUDRegisterObjectToNamespace("VKeyPress_J", VKeyPress_J)
    EUDRegisterObjectToNamespace("VKeyPress_K", VKeyPress_K)
    EUDRegisterObjectToNamespace("VKeyPress_L", VKeyPress_L)
    EUDRegisterObjectToNamespace("VKeyPress_SP3", VKeyPress_SP3)
    EUDRegisterObjectToNamespace("VKeyPress_O", VKeyPress_O)
    EUDRegisterObjectToNamespace("VKeyPress_SP4", VKeyPress_SP4)
    EUDRegisterObjectToNamespace("VKeyPress_Q", VKeyPress_Q)
    EUDRegisterObjectToNamespace("VKeyPress_R", VKeyPress_R)
    EUDRegisterObjectToNamespace("VKeyPress_S", VKeyPress_S)
    EUDRegisterObjectToNamespace("VKeyPress_T", VKeyPress_T)
    EUDRegisterObjectToNamespace("VKeyPress_SP2", VKeyPress_SP2)
    EUDRegisterObjectToNamespace("VKeyPress_V", VKeyPress_V)
    EUDRegisterObjectToNamespace("VKeyPress_W", VKeyPress_W)
    EUDRegisterObjectToNamespace("VKeyPress_X", VKeyPress_X)
    EUDRegisterObjectToNamespace("VKeyPress_Y", VKeyPress_Y)
    EUDRegisterObjectToNamespace("VKeyPress_Z", VKeyPress_Z)
    EUDRegisterObjectToNamespace("VChatIndex", VChatIndex)
EUDOnStart(Reg)
